@email = "123@123.123"
@password = "123"
@firstname = "1234"
@lastname = "1234"



### REGISTER
POST http://localhost:5000/accounts/register HTTP/2.1
Content-Type: application/json

{
    "email": {{email}},
    "firstname": {{firstname}},
    "lastname": {{lastname}},
    "password": {{password}},
    "confirmPassword": {{password}}
}

### LOGIN
# @name login
POST http://localhost:5000/accounts/login HTTP/2.1
Content-Type: application/json

{
    "email": {{email}},
    "password": {{password}}
}

###

@access_token = {{login.response.body.$.data.$.accessToken}}

### AUTHENTICATE USER
GET  http://localhost:5000/accounts/authenticate HTTP/2.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

### UPDATE
PUT http://localhost:5000/accounts/update HTTP/2.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "email": {{email}},
    "firstname": "njndfgdjnjghvcghvhgnjn",
    "lastname": "vvghvgh",
    "password": {{password}},
    "confirmPassword": {{password}}
}

### GET MYSELF
GET http://localhost:5000/accounts/me HTTP/2.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
