@email = "1234@1234.1234"
@password = "1234"
@firstname = "x"
@lastname = "v"



### REGISTER
POST http://localhost:5000/accounts/register HTTP/2.1
Content-Type: application/json

{
    "email": {{email}},
    "firstname": {{firstname}},
    "lastname": {{lastname}},
    "password": {{password}},
    "confirmPassword": {{password}}
}

### LOGIN
# @name login
POST http://localhost:5000/accounts/login HTTP/2.1
Content-Type: application/json

{
    "email": {{email}},
    "password": {{password}}
}

###

@access_token = {{login.response.body.$.data.$.accessToken}}

### AUTHENTICATE USER
POST http://localhost:5000/accounts/authenticate HTTP/2.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}